### PR TITLE
expr: improve clarity and consistency of help

### PR DESCRIPTION
**Pull request by ChrisHines**
Also fix some spelling errors.

### CODE REVIEW

**Comment by ChrisHines** [comment]
While researching how goda's various expressions work I began to wonder if the `test=1(X)` expression has been made obsolete by the `X:+test` selector. I couldn't find a difference in behavior. If they are the same then I suggest also replacing the `test=1(X)` entry in the `goda help expr` docs with the selector syntax since that seems newer, more flexible, and more intuitive.

**Comment by egonelbre** [comment]
Those are great fixes.

I do think that `X:+test` does make most common `test=1` use-cases obsolete. So, I'm all for using the `X:+test` in the examples.

The main difference is that the "environment modifier" allows to simplify some cases. For example `test=1(A + B - C)` instead of `A:+test + B:+test - C:+test`.

**Comment by ChrisHines** [comment]
> The main difference is that the "environment modifier" allows to simplify some cases. For example `test=1(A + B - C)` instead of `A:+test + B:+test - C:+test`.

Interesting.

Curiously `test=1(A + B)` is similar to `(A + B):+test`, except the second form includes `A.test` and `B.test`, but not `A [A.test]` or `B [B.test]`. The first form includes those as well.

**Comment by egonelbre** [comment]
Good catch. I missed the `A [A.test]` and `A_test [A.test]` in detecting whether it's a test package. Which does bring up an interesting question. Should they be considered as a test package, i.e. `A.test` and `A [A.test]`?

I guess it does make sense that `goda list A:test` and `goda list A` are disjoint. I guess if there's a need to differentiate, it's possible to add a new selector.

**Pull request merged**
